using DevExpress.Data;
using System;
using DevExpress.XtraSplashScreen;
using System.Windows.Forms;
using System.Threading;

namespace SQL_HELPER_APP
{
    public partial class Departmanlar : DevExpress.XtraEditors.XtraForm
    {
        public Departmanlar()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard

        }

        private void Grid_Load(object sender, EventArgs e)
        {
            BMS_DLL.DX.DXGRID_LOADLAYOUTFROM_REGISTIRY(gridControl1, "CIU", "GRID");
            gridControl1.DataSource = BMS_DLL.SQL.SELECT(@"SELECT LOGICALREF,CODE,DESCRIPTION,(SELECT DEPTNAME_ENG FROM BM_S_POSITIONS WHERE BM_S_POSITIONS.LOGICALREF=[S_POSITIONS].LOGICALREF ) DEPTNAME_ENG
FROM [S_POSITIONS]
 WITH(NOLOCK) ORDER BY CODE");
            gridView1.OptionsView.ColumnAutoWidth = false;
            gridView1.OptionsView.ShowFooter = true;

        }

        private void button1_Click(object sender, EventArgs e)
        {

        }

        private void Grid_FormClosing(object sender, FormClosingEventArgs e)
        {
            BMS_DLL.DX.DXGRID_SAVELAYOUTTO_REGISTIRY(gridControl1, "CIU", "GRID");
        }

        private void gridView1_PopupMenuShowing(object sender, DevExpress.XtraGrid.Views.Grid.PopupMenuShowingEventArgs e)
        {

        }


        private void simpleButton2_Click(object sender, EventArgs e)
        {
            BMS_DLL.DX.DXGRIDEXCELEKAYDET(gridView1, true);

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            for (int i = 0; i < gridView1.RowCount; i++)

            {

                try
                {
                    int LOGICALREF = int.Parse(gridView1.GetRowCellValue(i, "LOGICALREF").ToString());
                    string CODE = gridView1.GetRowCellValue(i, "CODE").ToString();
                    string DESCRIPTION = gridView1.GetRowCellValue(i, "DESCRIPTION").ToString();
                    string DEPTNAME_ENG = gridView1.GetRowCellValue(i, "DEPTNAME_ENG").ToString();
                    BMS_DLL.SQL.EXECUTE(this, string.Format(@"
   IF NOT EXISTS (SELECT * FROM BM_S_POSITIONS WHERE LOGICALREF={0})
    BEGIN
        INSERT INTO BM_S_POSITIONS(LOGICALREF,CODE, DESCRIPTION, DEPTNAME_ENG)
        Values({0}, '{1}', '{2}','{3}')
    END
    ELSE
    BEGIN
        UPDATE BM_S_POSITIONS SET DEPTNAME_ENG = '{3}' WHERE LOGICALREF = {0}
    END ", LOGICALREF, CODE, DESCRIPTION, DEPTNAME_ENG));
                }
                catch (Exception ex)
                {
                    BMS_DLL.GLOBAL.LOGYAZ("HATA", ex);
                }

            }
            MessageBox.Show("Kayıt Başarılı");
        }
    }
}